### PR TITLE
Add links to Sandia and NREL software indexes

### PR DESCRIPTION
**Pull request by kandersolar**

### CODE REVIEW

**Comment by kandersolar** [comment]
Are PR docs builds enabled?  This PR didn't seem to trigger a build: https://readthedocs.org/projects/openpvtools/builds/

**Comment by wholmgren** [comment]
I enabled them for a PR in the spring, but maybe I missed something. I just tried resyncing the github webhook and got a message "Webhook activation failed. Make sure you have the necessary permissions." I deleted it and recreated it. I'm at the end of my time for fumbling at the moment, but you should now have the ability to dig into it yourself :)

**Comment by kandersolar** [comment]
Thanks @wholmgren.  After some fumbling myself I got the PR build to trigger, but it still complained about the webhook being invalid and couldn't send a status back to this PR.  I think that may be because the RTD OAuth app doesn't have access to the `openpvtools` organization.  I requested access from the org owner (you?) in the RTD entry here: https://github.com/settings/applications

Regardless the PR build for this addition looks fine (I am never confident I got the RST link syntax correct...) so I'll go ahead and merge this.

**Comment by wholmgren** [comment]
I just granted it.

**Pull request merged**
