### PR TITLE
Adding pvfactors

### PR DESCRIPTION
**Pull request by anomam**
Hi @wholmgren , please let me know if anything else is needed.

### CODE REVIEW

**Comment by wholmgren** [comment]
Thanks @anomam! Any idea why the diff shows all lines changed instead of just the new addition? Unix vs. windows line endings?

**Comment by anomam** [comment]
I was actually wondering myself... I did it on Windows; I'll try to reset and push again tomorrow!

**Comment by anomam** [comment]
Hi @wholmgren , I just updated the file in a text editor and it looks better now. Let me know! Thanks

**Comment by wholmgren** [comment]
Awesome, thanks!

**Pull request merged**
